openai:
  base_url: "https://openrouter.ai/api/v1"
  api_key: "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"
model:
  name: "meta-llama/llama-3.3-70b-instruct:free"
  max_prompt_length: 131072
  batch_size: 8
  num_threads: 4
  timeout: 300
  base_url: "https://openrouter.ai/api/v1"
  openai_model: "meta-llama/llama-3.3-70b-instruct:free"
  bert_model: "bert-base-chinese"
  window_size: 30
  k_factors: 5
  bert_settings:
    max_length: 512
    padding: "max_length"
    truncation: True
    return_tensors: "pt"
    batch_size: 8

  gpu_settings:
    num_gpu_layers: 20
    batch_size: 8
    num_threads: 4
    memory_fraction: 0.8
    generation_settings:
      temperature: 0.7
      top_p: 0.9
      top_k: 40
      num_predict: 2048
  data_root: "data"

data:
  cn_stock: "600519.SH"
  us_stock: "AAPL"
  stocks:
    CN: ["600519.SH"]
    US: ["AAPL"]
  data_dir: "data"
  result_dir: "result"
  cache_dir: "cache"
  data_structure:
    price: "price.csv"
    news: "news.csv"
    factors: "factors.csv"
    predictions: "predictions.csv"
  start_date: "2021-12-20"
  end_date: "2021-12-22"
  preprocessing:
    remove_duplicates: true
    fill_missing: "ffill"
    normalize: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "logs/stock_prediction.log"
