model:
  name: "llama3.1:8b-instruct-q8_0"
  max_prompt_length: 131072
  batch_size: 8
  num_threads: 4
  timeout: 300
  ollama_url: "http://localhost:11434"
  ollama_model: "llama3.1:8b-instruct-q8_0"
  bert_model: "bert-base-chinese"
  bert_settings:
    max_length: 512
    padding: "max_length"
    truncation: True
    return_tensors: "pt"
    batch_size: 8
  window_size: 30
  k_factors: 5
  gpu_settings:
    num_gpu_layers: 20
    batch_size: 8
    num_threads: 4
    memory_fraction: 0.8
    generation_settings:
      temperature: 0.7
      top_p: 0.9
      top_k: 40
      num_predict: 2048
  data_root: "data"

data:
  cn_stock: "600519.SH"
  us_stock: "AAPL"
  stocks:
    CN: ["600519.SH"]
    US: ["AAPL"]
  data_dir: "data"
  result_dir: "result"
  cache_dir: "cache"
  data_structure:
    price: "price.csv"
    news: "news.csv"
    factors: "factors.csv"
    predictions: "predictions.csv"
  start_date: "2018-01-01"
  end_date: "2018-01-02"
  preprocessing:
    remove_duplicates: true
    fill_missing: "ffill"
    normalize: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "logs/stock_prediction.log"
  