model:
  window_size: 10
  k_factors: 5
  dataset: "Data"
  ollama_url: "http://localhost:11434/api/generate"
  ollama_model: "llama3.1:8b-instruct-q8_0"
  bert_model: "bert-base-chinese"
  data_root: "Data"

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "logs/stock_prediction.log"

data:
  start_date: "2018-01-01"
  end_date: "2018-03-01"
  stocks:
    CN: ["600519.SH"]
    US: ["AAPL"]